CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
username TEXT NOT NULL UNIQUE,
email_address TEXT NOT NULL,
password TEXT NOT NULL,
salt TEXT NOT NULL,
user_group TEXT NOT NULL);

DROP TABLE IF EXISTS users;